on: 
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v4

      - uses: levibostian/decaf@0.17.2
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          get_latest_release_current_branch: decaf shebang http://github.com/levibostian/decaf-script-github-releases.git/shebang.sh@1.3.0 get
          get_next_release_version: decaf shebang http://github.com/levibostian/decaf-script-conventional-commits.git/shebang.sh@0.3.0
          deploy: decaf shebang http://github.com/levibostian/decaf-script-github-releases.git/shebang.sh@1.3.0 set